-- Active: 1699024064604@@127.0.0.1@3306@the_new_shop

-- Write a SQL query to retrieve the total revenue generated by each product category. Display the category name along with the total revenue in descending order of the revenue.

SELECT
    c.name AS category_name,
    SUM(oi.quantity * oi.unit_price) AS total_revenue
FROM order_items oi
    INNER JOIN products p ON oi.product_id = p.id
    INNER JOIN categories c ON p.category_id = c.id
GROUP BY c.name
ORDER BY total_revenue DESC;